-- ============================================================
-- UrbanShield
-- MySQL Database Schema
-- ============================================================
--
-- Purpose:
--   Persistent storage for the UrbanShield urban crime
--   intelligence and decision-support system.
--
-- Data layers:
--   1. Historical incidents from the existing dataset
--   2. Incoming incidents submitted through the application/API
--
-- Main processing flow:
--
--   Incident
--       ↓
--   Risk Assessment
--       ↓
--   Anomaly / Hotspot Analysis
--       ↓
--   Alert Generation
--       ↓
--   Decision Support
--
-- This schema is designed for MySQL 8.x.
-- SQLAlchemy's database.py uses the same table structure.
--
-- ============================================================


-- ============================================================
-- 1. INCIDENTS
-- ============================================================
--
-- Stores both historical and newly received incidents.
--
-- source values used by the application:
--   historical
--   streamlit
--   api
--
-- status values may include:
--   Received
--   Submitted
--   Processed
--   Reviewed
--
-- ============================================================

CREATE TABLE IF NOT EXISTS incidents (

    id                  INT AUTO_INCREMENT PRIMARY KEY,

    incident_id         VARCHAR(32) NOT NULL UNIQUE,

    crime_type          VARCHAR(64) NOT NULL,

    crime_category      VARCHAR(32) NOT NULL,

    crime_severity      VARCHAR(32) NOT NULL,

    occurred_date       VARCHAR(16) NOT NULL,

    occurred_time       VARCHAR(16) NOT NULL,

    district             VARCHAR(64),

    neighborhood         VARCHAR(128),

    latitude             DOUBLE NOT NULL,

    longitude            DOUBLE NOT NULL,

    in_coverage          BOOLEAN DEFAULT TRUE,

    weapon_used          VARCHAR(32) DEFAULT 'Unknown',

    domestic_related     VARCHAR(8) DEFAULT 'No',

    gang_related         VARCHAR(8) DEFAULT 'No',

    property_damage      VARCHAR(8) DEFAULT 'No',

    estimated_loss       INT DEFAULT 0,

    priority_level       VARCHAR(16) DEFAULT 'Low',

    source               VARCHAR(16) DEFAULT 'streamlit',

    status               VARCHAR(32) DEFAULT 'Received',

    submitted_at         DATETIME DEFAULT CURRENT_TIMESTAMP,


    -- --------------------------------------------------------
    -- Indexes
    -- --------------------------------------------------------

    INDEX idx_incidents_incident_id (incident_id),

    INDEX idx_incidents_district (district),

    INDEX idx_incidents_crime_type (crime_type),

    INDEX idx_incidents_occurred_date (occurred_date),

    INDEX idx_incidents_submitted (submitted_at),

    INDEX idx_incidents_source (source),

    INDEX idx_incidents_status (status),

    INDEX idx_incidents_location (latitude, longitude)


) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 2. RISK ASSESSMENTS
-- ============================================================
--
-- Stores the risk calculated for an incident.
--
-- historical_risk:
--   District-level historical baseline.
--
-- dynamic_risk:
--   Current incident-specific risk score (0-100).
--
-- risk_level:
--   LOW
--   MODERATE
--   HIGH
--   CRITICAL
--
-- reasons:
--   JSON-encoded explanation generated by the risk engine.
--
-- ============================================================

CREATE TABLE IF NOT EXISTS risk_assessments (

    id                  INT AUTO_INCREMENT PRIMARY KEY,

    assessment_id       VARCHAR(32) NOT NULL UNIQUE,

    incident_id         VARCHAR(32) NOT NULL,

    historical_risk     DOUBLE NOT NULL DEFAULT 0,

    dynamic_risk        DOUBLE NOT NULL DEFAULT 0,

    risk_level          VARCHAR(16) NOT NULL,

    reasons              TEXT,

    anomaly_flag        BOOLEAN DEFAULT FALSE,

    anomaly_score       DOUBLE,

    created_at           DATETIME DEFAULT CURRENT_TIMESTAMP,


    -- --------------------------------------------------------
    -- Relationship
    -- --------------------------------------------------------

    CONSTRAINT fk_risk_incident
        FOREIGN KEY (incident_id)
        REFERENCES incidents(incident_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,


    -- --------------------------------------------------------
    -- Indexes
    -- --------------------------------------------------------

    INDEX idx_risk_incident (incident_id),

    INDEX idx_risk_level (risk_level),

    INDEX idx_risk_created (created_at),

    INDEX idx_risk_anomaly (anomaly_flag),

    INDEX idx_risk_dynamic (dynamic_risk)


) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 3. ALERTS
-- ============================================================
--
-- Stores warnings generated by UrbanShield.
--
-- Examples:
--
--   Risk Escalation
--   Elevated Risk
--   Anomaly
--   Emerging Hotspot
--   Early Warning
--
-- status:
--   Open
--   Acknowledged
--   Closed
--
-- ============================================================

CREATE TABLE IF NOT EXISTS alerts (

    id                  INT AUTO_INCREMENT PRIMARY KEY,

    alert_id            VARCHAR(32) NOT NULL UNIQUE,

    incident_id         VARCHAR(32),

    location             VARCHAR(128),

    alert_type           VARCHAR(32) NOT NULL,

    risk_level           VARCHAR(16) NOT NULL,

    message              TEXT NOT NULL,

    recommendation       TEXT,

    status               VARCHAR(16) DEFAULT 'Open',

    created_at            DATETIME DEFAULT CURRENT_TIMESTAMP,


    -- --------------------------------------------------------
    -- Relationship
    -- --------------------------------------------------------

    CONSTRAINT fk_alert_incident
        FOREIGN KEY (incident_id)
        REFERENCES incidents(incident_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,


    -- --------------------------------------------------------
    -- Indexes
    -- --------------------------------------------------------

    INDEX idx_alerts_incident (incident_id),

    INDEX idx_alerts_status (status),

    INDEX idx_alerts_risk_level (risk_level),

    INDEX idx_alerts_type (alert_type),

    INDEX idx_alerts_created (created_at)


) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- 4. AREA BASELINES
-- ============================================================
--
-- Stores the historical risk baseline for each district.
--
-- This table allows the system to distinguish:
--
--   Historical pattern
--             +
--   Current incoming activity
--             =
--   Dynamic risk
--
-- The baseline is periodically recomputed from the historical
-- dataset by the application.
--
-- ============================================================

CREATE TABLE IF NOT EXISTS area_baselines (

    id                          INT AUTO_INCREMENT PRIMARY KEY,

    district                    VARCHAR(64) NOT NULL UNIQUE,

    historical_incident_count   INT DEFAULT 0,

    avg_severity_score           DOUBLE DEFAULT 0.0,

    baseline_risk                DOUBLE DEFAULT 0.0,

    updated_at                   DATETIME DEFAULT CURRENT_TIMESTAMP
                                ON UPDATE CURRENT_TIMESTAMP,


    -- --------------------------------------------------------
    -- Indexes
    -- --------------------------------------------------------

    INDEX idx_baseline_district (district),

    INDEX idx_baseline_risk (baseline_risk)


) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


-- ============================================================
-- END OF URBANSHIELD SCHEMA
-- ============================================================